### ISSUE TITLE
Docker to resolve server dependency?

### ISSUE THREAD

**Issue by mc1098** [DA-Wishart/Fizzit.com#3]
So as #2 showed the code is dependent on what server version and could also be some config differences too in the future, especially when we address creating realms and such. 

Should we then use Docker in order to verify that the environment is correctly setup so that clones/pulls can be done and the DockerFile can create the correct environment for testing. It also documents what configurations have been made to the server too. 

I don't know if you guys have Docker installed? whether it's available on the Uni computers? 
What do you think?

**Comment by DeeDoubleYous** [comment]
having a glance at the functionality of Docker, it seems like a good tool. I wouldn't know about uni computers, but for our personal machines it would probably be best mentioning that the windows app it requires enterprise edition. So installing it for Linux/Windows subsystem for Linux and interacting with it via bash seems like the best way.

**Comment by mc1098** [comment]
It is bit awkward on windows without enterprise, but possible as I have it on my windows PC now. 
I think it needs to be on Uni computers so that it's easy to show and develop from those machines if required by others. 
I'll have to peek at the computers tomorrow and see if it has Docker (my feeling is that they won't).

**Comment by DeeDoubleYous** [comment]
at the very least docker is on the machines in c206 when in fedora. but that's not to say it's in any other room.

**Comment by mc1098** [comment]
Okay, that's a good sign. It would be great if it's in the lab for this project and really we need to get the view of the Olve and Nat so they are comfortable with it. I feel like once it's setup it would actually make it easier to jump on to help with code and such as the DockerFile will give all the actions required to get glassfish configured correctly.

**Comment by mc1098** [comment]
I've sent an email about getting Docker installed in C107, lets see what happens however I doubt this would happen in a timely manner to effect our project.
