### ISSUE TITLE
Trouble with deploying

### ISSUE THREAD

**Issue by DeeDoubleYous** [DA-Wishart/Fizzit.com#4]
So what's currently in the database branch is where I am at with just looking up the data from the database. Theoretically, it might work, but I can't get the project to deploy, it fails. I need an outside set of eyes to point at me and laugh at what I've done wrong,

**Comment by mc1098** [comment]
Okay I shall have a look at it. 
The database realm..did you do it by gui or command line?
Can you remove the ide specific folders from the branch. (.settings, bin, .classpath, .project).

**Comment by DeeDoubleYous** [comment]
Its set up via the GUI,
These are the additional properties I have set and no other changes to the connection pool.
![image](https://user-images.githubusercontent.com/7958479/75635418-dc629580-5c0d-11ea-9113-25231d7bafb3.png)

**Comment by mc1098** [comment]
Add those files to the .gitignore file to stop them from creeping back into to future commits.

**Comment by mc1098** [comment]
I have updated the database branch and was able to successfully deploy and connect to the database. There is still things to be changed to complete the requirement but the update should resolve this particular issue.

**Comment by mc1098** [comment]
This has been resolved.
